export const LOGIN_ENDPOINT = process.env.NEXT_PUBLIC_LOGIN_ENDPOINT;
export const DASHBOARD_ENDPOINT = process.env.NEXT_PUBLIC_DASHBOARD_ENDPOINT;
export const EMPLOYEE_ENDPOINT = process.env.NEXT_PUBLIC_EMPLOYEE_ENDPOINT;
export const USER_ENDPOINT = process.env.NEXT_PUBLIC_USER_ENDPOINT;
export const SERVICE_ENDPOINT = process.env.NEXT_PUBLIC_PRODUCTS_ENDPOINT;
export const CATEGORY_ENDPOINT = process.env.NEXT_PUBLIC_CATEGORIES_ENDPOINT;
