import type { Metadata } from "next";
import "./globals.css";
import { federo, lora } from "@/app/components/fonts";
import Providers from "./providers";
import { Toaster } from 'sonner';

export const metadata: Metadata = {
  title: "CMS Addo Salon",
  description: "Generated by fakhri fajar",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lora.className} ${federo.className} antialiased`}
      >
        <Providers>
          {children}
          <Toaster position="top-center" richColors toastOptions={{
            duration: 3000,
          }} />
        </Providers>
      </body>
    </html>
  );
}
